#!/bin/bash

_project_=yodl
_product_=yodl

git co master

cd ${_product_}
./build programs
./build macros
./build man
./build html

./build github
./build distclean
cd ..    
git co gh-pages

cp -r ../wip/changelog.txt ../wip/man ../wip/yodl-doc .

yodl2html index.yo || exit 1

echo "Running 'git st': no untracked files or ignorable files should be shown"
git st

echo

echo -n "git ci changes to index.html etc., push the result and \
git co master [y/n] ? "

read yesno

if [ "$yesno" == "y" ] ; then

    RELEASE=`head -n1 ../wip/release.yo | 
                sed 's/SUBST(_CurVers_)(\(.*\))/\1/'`

    msgDefault="gh-pages for release ${RELEASE}"

    echo -n "Enter the ci message [default: $msgDefault]"

    read msg;

    [ "$msg" == "" ] && msg=$msgDefault

    git ci -am "$msg"
    git push
    git co master
fi


