#!/bin/bash

[ $# != 2 ] && echo "Usage: $0 xxx.in xxx.yo" && exit 1

CONFIG="tmp/wip/config.h"

STD_INCLUDE=`grep "#define[[:space:]]\+STD_INCLUDE" $CONFIG | \
            sed 's,.*STD_INCLUDE[[:space:]]\+\"\([^"]\+\)".*,\1,'`

YODL_BIN=`grep "#define[[:space:]]\+YODL_BIN" $CONFIG | \
            sed 's,.*YODL_BIN[[:space:]]\+\"\([^"]\+\)".*,\1,'`

VERSION=`grep "#define[[:space:]]\+VERSION" $CONFIG | \
            sed 's,.*VERSION[[:space:]]\+\"\([^"]\+\)".*,\1,'`

sed '
s,@STD_INCLUDE@,'$STD_INCLUDE',g
s,@YODL_BIN@,'$YODL_BIN',g
s,@VERSION@,'$VERSION',g
' $1 > $2



