#!/bin/bash

CONFIG="tmp/wip/config.h"

case $# in
    (2)
        STD_INCLUDE=`grep "#define[[:space:]]\+STD_INCLUDE" $CONFIG | \
                    sed 's,.*STD_INCLUDE[[:space:]]\+\"\([^"]\+\)".*,\1,'`

        # keep as is
    ;;
    
    (3)
        STD_INCLUDE=$3
    ;;

    (*)
        echo "Usage: $0 xxx.in xxx.yo [actual-path-to-macro-files]"
        exit 1
    ;;
esac

YODL_BIN=`grep "#define[[:space:]]\+YODL_BIN" $CONFIG | \
            sed 's,.*YODL_BIN[[:space:]]\+\"\([^"]\+\)".*,\1,'`

VERSION=`grep "#define[[:space:]]\+VERSION" $CONFIG | \
            sed 's,.*VERSION[[:space:]]\+\"\([^"]\+\)".*,\1,'`

sed '
s,@STD_INCLUDE@,'$STD_INCLUDE',g
s,@YODL_BIN@,'$YODL_BIN',g
s,@VERSION@,'$VERSION',g
' $1 > $2



